### ISSUE TITLE
Git clone failing: "error authenticating: failed connecting agent"

### ISSUE THREAD

**Issue by li-cn** [nodegit/nodegit#1040]
I'm running nodegit from an Electron project. When I try to clone a repository I want to open, I get an error message: `[Error: error authenticating: failed connecting agent]`.

Here's the code I'm running to clone the repository I want:

```javascript
Clone('<my repository url>', '<destination directory>', {
  fetchOpts: {
    callbacks: {
      credentials: (url, username) => Cred.sshKeyFromAgent(username)
    }
  }
})
```

I generated a new SSH key, added the public key to the deployment keys for the Bitbucket repository I'm pulling from, and then ran the following in Git Bash before starting the program:

```
eval $(ssh-agent -s)
ssh-add ~/.ssh/id_rsa
```

Anyone have any idea what the issue might be? A quick Google search turns up nothing useful for this error message.

I'm running Node v6.2.0 on Windows 10, with Electron v0.37.8, and nodegit v0.13.0. Thanks in advance!

**Comment by maxkorp** [comment]
Nodegit will only listen for pageant on windows, not openssh's ssh-agent. That stems all the way upstream to libssh2, so not a lot we can do about that unfortunately.

**Comment by computerquip-streamlabs** [comment]
While this problem may not be fixable from this point of view, I'd still think this qualifies as an issue as I would assume more than a few people setup keys on Windows using the ssh-agent provided with git bash.

I think the issue should be re-opened to spark interest in a fix upstream if that is where the problem lies. Unfortunately, this problem is a deal breaker for me and I can't use the software as is. 

That said, there appears to be an example of ssh-agent authentication here: https://www.libssh2.org/examples/ssh2_agent.html
