### ISSUE TITLE
index.addByPath() complains. The index is locked. This might be due to a concurrent or crashed process

### ISSUE THREAD

**Issue by velgergarb** [nodegit/nodegit#1043]
I believe this is a permissions issue.  In desperation, I tried to chmod the index, but that did not take effect.  Any suggestions on how I can avoid or overcome this problem?

**Comment by johnhaley81** [comment]
@velgergarb you have to control access to writing to the index in your application. When writing to the index there is a possibility that some other git client is also writing to the index, or another function in your app is trying to write to the index. You could implement a semaphore lock for all index writes that wait for the lock to be available before obtaining the lock themselves and writing to the index. Or you could chain all of the index writes in a `Promise` and make sure that they are all waiting on previous ones to finish before moving on.

libgit2 decided to make index locking not a library responsibility and we also share that policy. We can't control for everything an application is trying to do to the index so that task is yours and how you decide to solve it.
