### ISSUE TITLE
lifecycleScripts/preinstall.js weird npm check

### ISSUE THREAD

**Issue by philkunz** [nodegit/nodegit#1063]
lifecycleScripts/preinstall.js

Why is there a test for the npm version in line 13 for which npm version is installed? It causes my builds to fail, removing this check lets them pass just fine... meaning **with the check in place npm 3 works fine**, npm 2 fails.

In other words why is npm 3 handled differently from npm 2?

**Comment by johnhaley81** [comment]
When you override npm lifecycle scripts things behave differently in npm@2 and npm@3. With 3 you'll still install all packages under `dependencies` but with 2 you have to explicitly ignore the scripts to install them. Since the lifecycle scripts themselves require those packages they must be installed before the script continues.

How is it breaking for you?

**Comment by philkunz** [comment]
Its a pretty old build log, so in newer builds I fixed this behaviour by defaulting to npm3 in all preinstalled node versions of the docker base image that the tests run in:

But the error I'm seeing when using npm2 is here:
https://gitlab.com/pushrocks/smartgit/builds/2014887

**Comment by philkunz** [comment]
So I think for some reason something goes wrong with the path and it isn't able to resolve the path to the local vendor/openssl...

**Comment by philkunz** [comment]
Why not move all of this stuff to a postinstall script?
