### ISSUE TITLE
Writing index after merge throws error

### ISSUE THREAD

**Issue by highco** [nodegit/nodegit#1128]
When running examples/merge-cleanly.js, the following error is thrown by index.write():
Uncaught Error: Failed to write index: The index is in-memory only
Either index.write() or the example is broken.

**Comment by alangpierce** [comment]
@highco I ran into this same issue and ended up solving by using the `Merge.merge` function instead of `Merge.commits`. One problem that took me a while to track down is that you need to specify `Checkout.STRATEGY.FORCE` (or some other non-default strategy) or else it won't change your working directory you'll end up with a completely empty merge commit.

Here's a code snippet that hopefully is helpful:

```js
async function createMergeCommit(repo, otherCommit, mergeMessage) {
  const annotatedCommit = await nodegit.AnnotatedCommit.lookup(repo, otherCommit.id());
  await nodegit.Merge.merge(repo, annotatedCommit, null, {
    checkoutStrategy: nodegit.Checkout.STRATEGY.FORCE,
  });
  const index = await repo.refreshIndex();
  if (index.hasConflicts()) {
    throw new CLIError('Unexpected conflict when creating merge commit.');
  }
  await index.write();
  const treeOid = await index.writeTree();
  await repo.createCommit(
    'HEAD',
    repo.defaultSignature(),
    repo.defaultSignature(),
    mergeMessage,
    treeOid,
    [await repo.getHeadCommit(), otherCommit]
  );
  repo.stateCleanup();
}
```

Full example here:
https://github.com/alangpierce/bulk-decaffeinate/blob/master/src/land.js
