### ISSUE TITLE
bind Repository with HTTP?

### ISSUE THREAD

**Issue by Bizarrus** [nodegit/nodegit#1207]
It is possible to bind the Repository over HTTP to access it over http(s)://domain.tld/User/Repo.git?

**Comment by maxkorp** [comment]
For a clone example, see here: https://github.com/nodegit/nodegit/blob/master/test/tests/clone.js#L31

Skipped because github forces over to https, but thats how transport is handled using cloning as an example.

If you need further support, hit us up in our slack channel in the libgit2 slack 
https://slack.libgit2.org
