### ISSUE TITLE
Adding directories

### ISSUE THREAD

**Issue by DawsonG** [nodegit/nodegit#121]
Following the add-and-commit.js in the example directory I was able to get my own application adding addByPath to commit new files.  However, addByPath doesn't work on directories.  Is there a way to add a whole directory to a repository?

**Comment by rolandjitsu** [comment]
@maxkorp so you can use `addByPath()` to add an entire directory? Because I see the same error reported here when I try to add a dir.

**Comment by rcjsuen** [comment]
Yup, this is not working. The [changes to the example](https://github.com/nodegit/nodegit/pull/283/files) doesn't actually cover the case of passing a directory into `addByPath`, it's only checking for something like `folder/file.txt`.

```
[Error: cannot create blob from '/blah/blah/test-repo/tmp'; it is a directory]
```

```JavaScript
var git = require("nodegit");

git.Repository.open("test-repo")
.then(function(r) {
	return r.index();
}).then(function(index) {
	return index.addByPath("tmp");
}).then(function(ret) {
	console.log("good");
	console.log(ret);
}).catch(function(err) {
	console.log(err);
});
```

Since the JavaScript implementation is a direct wrapper of [```git_index_add_bypath```](https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_add_bypath) and not a custom implementation, this is no surprise as the libgit2 API only takes a filename and not a directory name.

The [`addByPath(*)`](http://www.nodegit.org/api/index/#addByPath) function should either be enhanced to take in a directory name or a completely new API function should be created for handling this case.

**Comment by rolandjitsu** [comment]
@rcjsuen I agree. The `.addAll()` function supports globs though, so that's an alternative. But that command fails as well if you pass in just a folder.

**Comment by xiaobeiHan** [comment]
Hi, if i want to add several files, such as   a/b/text1.js,  c/d/test2.js . How can I do using the add functions?

**Comment by xiaobeiHan** [comment]
@DawsonG Hi, if i want to add many files, such as a/b/text1.js, c/d/test2.js ...  How can I do using the add functions? Can i add an Array of filePaths ?
