### ISSUE TITLE
feature request: callback API

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodegit/nodegit#1221]
I was wondering why `nodegit` provides a promise only API. Callback options and/or promisification should be fairly simple. Would there be any chance to employ this?

**Comment by rcjsuen** [comment]
In your ideal callback API, what would a simple 3-step "adding a file", "staging a file", and "committing" look like in your mind? Can you provide some sample code as to what you are thinking of? Promises are very similar to callbacks so I am curious as to what you have in mind.

**Comment by maxkorp** [comment]
I think bluebird offers some sort of depromisify functionality.

**Comment by eljefedelrodeodeljefe** [comment]
I don't think bluebird has something like that (after looking at it).
Also after just wanting to integrate this module into a larger application, I again had the feeling that it's unusable due to the context switch of promises. You simply can't really integrate it in a normal callback style application. So it would be beneficial let alone for market share to have this.

As to the example. The one from README would look like this:
```js
var Git = require("nodegit");

// Clone a given repository into the `./tmp` folder.
Git.Clone("https://github.com/nodegit/nodegit", "./tmp", (err, repo) => {
  if (err) {
    return console.log(err)
  }

  repo.getCommit("59b20b8d5c6ff8d09518454d4dd8b7b30f095ab5", (err, commit) => {
    if (err) {
      return console.log(err)
    }

    commit.getEntry("README.md", (err, entry) => {
      if (err) {
        return console.log(err)
      }

      entry.getBlob((err, blob) => {
        if (err) {
          return console.log(err)
        }

        blob.entry = entry

        // Show the path, sha, and filesize in bytes.
        console.log(blob.entry.path() + blob.entry.sha() + blob.rawsize() + "b");

        // Show a spacer.
        console.log(Array(72).join("=") + "\n\n");

        // Show the entire file.
        console.log(String(blob));
      })
    })
  })
})

```

Looks like nod.js to me and can be abstracted with some async helper libraries to mitigate callback hell, if that is something you wanted to do with the promise API.

**Comment by eljefedelrodeodeljefe** [comment]
I am no pro on Promises, but I think the above would just require arg-length branching here, no? https://github.com/nodegit/nodegit/blob/master/lib/clone.js#L44-L46

**Comment by rcjsuen** [comment]
I rewrote your example code with the current promise support, @eljefedelrodeodeljefe. I guess your issue is that the error handling code has to be done at the end...?

```JavaScript
Git.Repository.open(".").then((repo) => {
  repo.getCommit("...").then((commit) => {
    commit.getEntry("README.md").then((entry) => {
      entry.getBlob().then((blob) => {
        blob.entry = entry

        // Show the path, sha, and filesize in bytes.
        console.log(blob.entry.path() + blob.entry.sha() + blob.rawsize() + "b");

        // Show a spacer.
        console.log(Array(72).join("=") + "\n\n");

        // Show the entire file.
        console.log(String(blob));
      }, (err) => {
        console.log(err);
      });
    }, (err) => {
      console.log(err);
    });
  }, (err) => {
    console.log(err);
  });
}, (err) => {
  console.log(err);
});
```

**Comment by maxkorp** [comment]
http://bluebirdjs.com/docs/api/ascallback.html is what I was thinking of. Not quite a full on callback api, but can be used as such. 

`promisify-node` is intended to allow callbacks or promises on automatically promisified functions, but that code seems a bit broken in regards to other optional arguments and our C++ guarding. Arg length branching is a problem for this reason anyways, since we support omitting arguments as it is. As far as I can tell it is non-traditional at best to provide both apis through the same function the way we do, although I think that decision was made before that standard really became normalized throughout the community. Additionally, numerous javascript helpers are promise only. 

There is a substantial bit of work involved in making this available. I am by no means adverse to it, although the other @owners might have other input. Changing names of functions to represent being promisified as is standard would be *extremely* breaking and I *am* opposed to that. However, perhaps an automatic addition of asCallback methods would be nice, e.g. `Clone.clone` which returns a promise still, and `Clone.cloneAsCallback` which takes a callback method. This would probably have to be done dynamically in `lib/nodegit.js` (which comes from a template file somewhere in `generate`). 

@owners does anybody have any opposition to that? @eljefedelrodeodeljefe I don't see anybody prioritizing that, but unless somebody here says otherwise (and possibly even then with some work) a PR would most likely be welcome.

**Comment by eljefedelrodeodeljefe** [comment]
I am assume [callbackify](https://github.com/nodejs/CTC/issues/109) will land at some point. Would use it then...
