### ISSUE TITLE
%1 is not a valid Win32 Application

### ISSUE THREAD

**Issue by Cyval** [nodegit/nodegit#1256]
Hi. I searched for solutions on the Internet but I found none. 

I am running a Windows 7 x64 OS, and am using Meteor for development with this awesome library. 
I always get this error whenever I run "meteor --settings settings.json":

```
Error : %1 is not a valid Win32 application
\\?\C;\Users\[myusername]\External\_code-editor\node_modules\nodegit\build\Release\nodegit.node
```

I tried the following : 
```
npm install npm -g
deleted node_modules
npm install
meteor npm install
```
but to no avail. How can I fix this? Thanks

**Comment by rcjsuen** [comment]
This sounds like a 32-bit and 64-bit mismatch issue...?

Are you using a 32-bit Node.js to run a 64-bit NodeGit binary?
Are you using a 64-bit Node.js to run a 32-bit NodeGit binary?

**Comment by Cyval** [comment]
Hi thanks for the comment. I reinstalled nodegit with the flag `--msvs_version=2017` , and this error appears : "cannot find module build/release/nodegit.node". Should I do a npm rebuild?

**Comment by Mklueh** [comment]
I have the same issue trying to use nodegit within Meteor

**Comment by maxkorp** [comment]
Can somebody provide a quick sample repo to test this with?

**Comment by Mklueh** [comment]
In my case I got it working.

The reason was that Meteor uses it´s own 32 bit node by default, but the Webstorm IDE uses the one installed in the system which is in my case 64 bit.

So it was my mistake to install dependencies with the build-in commands in the Webstorm context menu instead of using **meteor npm install**. Now nodegit seems to be compiled for 32 bit too and it works ;)

**Comment by saper** [comment]
thank you @mklueh
