### ISSUE TITLE
Documentation falling behind releases

### ISSUE THREAD

**Issue by JimiC** [nodegit/nodegit#1402]
I was @ http://www.nodegit.org/api/ and noticed that the release version and the doc version don't match.
Investigating further the issue, I discovered that the problem lies in [`.travis.yml`](https://github.com/nodegit/nodegit/blob/master/.travis.yml#L101).

Would you guys accept a PR to fix this or is it something done deliberately?

**Comment by rcjsuen** [comment]
@JimiC As far as I know, there is nothing intentional about this. I think the maintainers just forgot to update this. Note that the website itself is hosted in the [nodegit/nodegit.github.com](https://github.com/nodegit/nodegit.github.com) repository.

@johnhaley81 updated the website in the past so perhaps he can comment on this.

**Comment by Croydon** [comment]
Auto generated documentation can, and properly should, be updated automatically via Travis. Advantages: Always up-to-date and no manually work.

**Comment by JimiC** [comment]
To provide further info, currently `travis` configuration states:

In line 101
```sh
- if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION == "6" ] && [ $TARGET_ARCH == "x64" ]; then
      .travis/deploy-docs.sh;
    fi
```
but the `env.matrix` doesn't contain a `NODE_VERSION` of 6.

**Comment by Croydon** [comment]
The coveralls check is similar broken. I will create a pull request if my CI is running green.

**Comment by rcjsuen** [comment]
It doesn't like your suggestion, @JimiC. I guess we'll just have to stick to `==`.
```Bash
$ if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION =~ ^6 ] && [ $TARGET_ARCH == "x64" ]; then .travis/deploy-docs.sh; fi
/home/travis/.travis/job_stages: line 57: [: =~: binary operator expected
```
```Bash
$ if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION =~ "^6" ] && [ $TARGET_ARCH == "x64" ]; then .travis/deploy-docs.sh; fi
/home/travis/.travis/job_stages: line 57: [: =~: binary operator expected
```

**Comment by JimiC** [comment]
Ah yes the binary operator issue, it's easily resolved by using `[[ $NODE_VERSION =~ ^6  ]]`

**Comment by Croydon** [comment]
Or https://github.com/inexorgame/nodegit/commit/06036580127ae7806ee38d932505a964a284ed29

**Comment by Croydon** [comment]
The tests are currently failing.

I'm not familar with this stuff, but a quick search suggests that the --coverage flags needs to get passed along to gcc

https://travis-ci.org/inexorgame/nodegit/jobs/346897748#L9359

Has someone an idea how to fix this?

**Comment by rcjsuen** [comment]
@Croydon Let's fix the documentation and then address the coverage in another issue.

**Comment by JimiC** [comment]
I'll have a look at it in the morning.

**Comment by JimiC** [comment]
@Croydon @rcjsuen Should the docs be updated on every change or on a release?

**Comment by rcjsuen** [comment]
@JimiC In order of best to worse, I would say:

1. Both. It should be possible to view the documentation of what's in `master` as well as the latest release. I don't know how [libgit2](https://libgit2.github.com/libgit2) does their documentation but that's what happens. It defaults to the documentation of `HEAD` but you can also look at the documentation of a previous release. This would of course require changes to the website in its current form.
2. They should be updated when a new release happens. Generally speaking, people that are looking up API expects it to match a release version instead of a moving target.
3. They should be updated every time `master` changes. This is likely the simplest but can be confusing for readers. It's better than being outdated though in my opinion.

Before any of this can proceed, the `GH_TOKEN` environment variable would have to be defined first though. Please see #793 for the original pull request that introduced this the `deploy-docs.sh` script.

**Comment by JimiC** [comment]
@rcjsuen Thanks for clarifying. I see that there are a lot of moving parts in this. Indeed I noticed that the automation never got activated. I'll do my best to have this working.

**Comment by JimiC** [comment]
@rcjsuen Looking at the docs, for starters I'll target option 2, as currently the way docs are generated do not support `release` and `latest` versions.

**Comment by rcjsuen** [comment]
I'm not sure if the [tag build (Travis CI build #3120)](https://travis-ci.org/nodegit/nodegit/builds/355619875) deployed the documentation.

```
travis_time:end:2809b14a:start=1521505081593689828,finish=1521505093648749472,duration=12055059644
[0Ktravis_fold:end:after_success.1
[0Ktravis_fold:start:after_success.2
[0Ktravis_time:start:19ba2843
[0K$ if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ -n "$TRAVIS_TAG" ] && [ "$DEPLOY_DOCUMENTATION" == "true" ]; then .travis/deploy-docs.sh; fi

travis_time:end:19ba2843:start=1521505093657386778,finish=1521505093664643888,duration=7257110
[0Ktravis_fold:end:after_success.2
[0K
Done. Your build exited with 0.
```
