### ISSUE TITLE
Build from source fails: "Cannot find module 'walk'"

### ISSUE THREAD

**Issue by Mklueh** [nodegit/nodegit#1418]
Hi, I´m currently trying to build this project again from source. It worked once I tried it but currently it doesn´t anymore.

I´m on debian stretch within a docker image

This is the error I´m getting

> root@c3e4ca313ff7:/home/meteor/bundle/bundle/programs/server/npm/node_modules/nodegit/nodegit# meteor npm install  --unsafe-perm
> 
> > nodegit@0.20.3 install /home/meteor/bundle/bundle/programs/server/npm/node_modules/nodegit/nodegit
> > node lifecycleScripts/preinstall && node lifecycleScripts/install
> 
> [nodegit] Running pre-install script
> [nodegit] Configuring libssh2.
> [nodegit] ERROR - Could not finish preinstall
> { Error: Cannot find module 'walk'
>     at Function.Module._resolveFilename (module.js:536:15)
>     at Function.Module._load (module.js:466:25)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/meteor/bundle/bundle/programs/server/npm/node_modules/nodegit/nodegit/generate/scripts/utils.js:2:14)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3) code: 'MODULE_NOT_FOUND' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nodegit@0.20.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nodegit@0.20.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /.npm/_logs/2017-12-25T12_41_56_439Z-debug.log
> 

I´ve also tried to install the walk module globally which doesn´t help. Any idea how I get this working or is the master currently broken?

**Comment by Mklueh** [comment]
I´ve added walk to my application package.json which worked, but now I get

> Error: Cannot find module 'combyne'

**Comment by Mklueh** [comment]
After adding

>   "walk": "^2.3.9",
>     "combyne": "^2.0.0",
>     "js-beautify": "^1.7.5"

It finally works....

**Comment by luii** [comment]
Did you try to run just `meteor npm install --ignore-scripts` to install just the dependencies?

If so, are you in an production environment and have may set any production flags which may alter the installation process. Because all of the dependencies from above are used in the generate scripts (generate*) and are devDependencies.

You can also try to set `NODE_ENV=development` which would force it to be a dev environment.

If built my own nodegit build script in [luii/nodeos-nodegit](https://github.com/luii/nodeos-nodegit)
and the build process is very simple and devDependencies wont be installed unless you force it to do so, so it must be a production environment.

**Comment by Mklueh** [comment]
Happy new year @luii ;) --ignore-scripts has indeed worked. Thank you very much!!

**Comment by luii** [comment]
@Mklueh Good that i can help, happy new year to you too!
