### ISSUE TITLE
deployment/nodegit/generate/templates/templates/nodegit.js:28:1: Unexpected > token (28:1)

### ISSUE THREAD

**Issue by Mklueh** [nodegit/nodegit#1419]
I honestly don´t know what I´m doing wrong with this project. I´m running in every possible error that can happen, it almost seems like a curse lol

I´m using it in my Meteor application I´m about to deploy with Docker. My base image is Debian Stretch.
Now that there is this NPM issue #1392 I´m forced to build it from source. The first thing I ran into was this #1418 . Dependencies were missing although they do exist in the package.json of the project.

After adding them to my own project separately I´m now running into this. It seems "Jshint ignore" is ignored.

> Errors prevented bundling:
> While processing files with ecmascript (for target web.browser):
> deployment/nodegit/generate/templates/templates/enums.js:4:1: Unexpected token
> (4:1)
> deployment/nodegit/generate/templates/templates/nodegit.js:28:1: Unexpected
> token (28:1)
> 
> While processing files with ecmascript (for target os.linux.x86_64):
> deployment/nodegit/generate/templates/templates/enums.js:4:1: Unexpected token
> (4:1)
> deployment/nodegit/generate/templates/templates/nodegit.js:28:1: Unexpected
> token (28:1)
> 

I´m using this commit #b6e1478accf832f7982d3ce94fa3b98acf7ac8be because it´s build succeeded with Travis and building it with "meteor npm install --unsafe-perm". (same as npm install, it just uses the npm 5.5.1 on Node v8.9.3 of Meteor)

What am I doing wrong? Help is much appreciated, thank you

**Comment by luii** [comment]
It seems you've run in an error when [generateNativeCode](nodegit/generate/scripts/generateNativeCode.js ) was run.

The only part where this path are used are in the script above, which gets called from [here](https://github.com/nodegit/nodegit/blob/master/lifecycleScripts/preinstall.js#L24-L31)
so it dont matters how you call it, you need to build it from source using the environment variable `BUILD_ONLY=1` if you dont `git clone ...` it because it sets some varaibles internally (BUILD_ONLY=1 == git clone; means if you npm install it you need BUILD_ONLY, if you clone it you dont need BUILD_ONLY)

Also please make sure to be in an development environment because `devDependencies` wont be installed unless you have a Flag set (like NODE_ENV=production; or so).

**Comment by Mklueh** [comment]
See #1418
