### ISSUE TITLE
Get commit author date, rather than committer date

### ISSUE THREAD

**Issue by garyking** [nodegit/nodegit#1542]
When I amend a commit, its date in the `.date()` method gets updated. Please give us an option to also retrieve the original, author date for a commit, too.

It seems like `git log` actually defaults to showing the author date too, rather than the committer date.

**Comment by rcjsuen** [comment]
@garyking To get the author's information or the committer's information, simply use `commit.author().when()` or `commit.committer().when`().

As to your issue about amending, how would you get the original, pre-amended commit's date information from the CLI `git`?

**Comment by garyking** [comment]
Thanks, that method worked. I can't find the method in the docs though. 

And, I mean the original creation date of the commit. That's the "author date" I assume. While the "committer date" is basically the last time the commit was touched.

**Comment by maxkorp** [comment]
Pedantically speaking, "the last time the commit was touched" and "the original creation date of the commit" are the same, as a touched commit is an entirely new commit.

The idea carries semantic value though, and you are exactly correct in that author date is meant to provide that information.  When a commit is amended or otherwise recreated (rebased etc), the new commit takes the "source" commit's author info as its own. In the case of a new from scratch commit, that's the same as the commiter info, obviously. 

I'll make an issue in the docs repo that author info is seemingly missing.
