### ISSUE TITLE
Can't install nodegit with node 13.7

### ISSUE THREAD

**Issue by ablakey** [nodegit/nodegit#1753]
I think the most telling part of the error log is this:

```
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.4 and node@13.7.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
/bin/sh: 1: krb5-config: not found
```
The problem goes away with older versions of node, probably because the prebuilts exist.  So I'm betting this issue is a mix of: prebuilts for 13.7 don't exist yet and you're missing `krb5-config` which is required to manually compile them.

Here's the whole error:
```
 nodegit@0.26.4 install /home/username/repos/unnamed_project/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.4-node-v79-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.4 and node@13.7.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp
ERR! configure error
gyp
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/username/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack
at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp
ERR! System Linux 5.0.0-37-generic
gyp ERR! command "/home/username/.nvm/versions/node/v13.7.0/bin/node" "/home/username/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /home/username/repos/unnamed_project/node_modules/nodegit
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v
v5.0.5
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/username/.nvm/versions/node/v13.7.0/bin/node /home/username/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/username/repos/unnamed_project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.0.0-37-generic
node-pre-gyp ERR! command "/home/username/.nvm/versions/node/v13.7.0/bin/node" "/home/username/repos/unnamed_project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/username/repos/unnamed_project/node_modules/nodegit
node-pre-gyp ERR! node -v v13.7.0
node-pre-gyp ERR!
node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/home/username/.nvm/versions/node/v13.7.0/bin/node /home/username/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/username/repos/unnamed_project/node_modules/nodegit/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
```

**Comment by implausible** [comment]
Yes, you'd be correct. You will need to install krb5-config to get NodeGit building on node 13 at the moment.

I'm usually a bit slow at adopting odd versioned releases from Node as they are typically experimental and shortlived (~6 months lifespan).

**Comment by ablakey** [comment]
Thanks for teaching me something new. I should stick with even numbered versions too then!

**Comment by einfallstoll** [comment]
@implausible It would be helpful to have this statement in the README or a list of pre-built binaries. I was looking for it, but couldn't find.

**Comment by implausible** [comment]
Fair enough. I think adding documentation that we aim to provide prebuilts for even-numbered Node builds would be helpful in general.

**Comment by jods4** [comment]
@implausible When are you going to provide binaries for Node 14?
I tried to install nodegit and it failed with "Pre-built binaries not found".

Nodegit homepage says _"NodeGit can be quickly and painlessly installed via NPM."_ but I find that to be just untrue.

Not having pre-built binaries means node-gyp building the lib, which means having Python installed, blah blah blah.

NodeGit is useful, but there's nothing quick or painless about its installation. In fact, I can't use it right now (since I have Node 14, the build fails and I'm not gonna install stuff just to fix it).

**Comment by implausible** [comment]
@jods4 Hi there. I want you to take a step back and reread your request to this project a little more carefully. I want you to try and view your comment through the eyes of someone who maintains this project on an as-required basis at work and on a volunteer basis outside of work. I am under no obligation to fulfill any request that you might have of this project. Taking that into consideration, under what world do you feel that your comment is an appropriate way to make a simple request/reminder to add a prebuilt for Node 14? Did you write this, step back, and say, yes! This is the thing that will convince the maintainers to do what I want them to do! Yes! This is a rock solid argument, I won the internet! I want to inform you that it is not and was an incredibly rude approach to requesting anything from this project.

Unfortunately, I am very busy at work at the moment, and I am also experiencing some hefty life changes outside of work - so my time is rather limited for the project at the moment. I will not be able to add prebuilts for Node 14 until things have calmed down a bit for me. In the meantime, the library is incredibly easy to install. NPM has for a long time advised about native node modules and the node-gyp dependency that they come with. You might want to review the documentation there to get some insight into what dependencies you need to build for Node 14. I would also recommend you read our README.md for any additional build time dependencies you might need.

If you run into any compatibility errors with Node 14, you are welcome to try opening a more polite issue or request to address the compatibility problems. In the meantime, I will try to get a Node 14 build out sometime this month (as my time permits).

**Comment by einfallstoll** [comment]
@implausible First of all thanks for your work and this is an awesome reply. I fully agree with you.

I think nodegit is very easy to install (maybe the build time for odd-versioned node is indeed a bit painful) and I think pre-built binaries targeting the current LTS (12 at the time) is what we can expect and makes sense. Node.js 14 only gets into LTS in October, so there's plenty of time left and I wouldn't rush with this.

Maybe you can update the package to reflect this in the meantime:

`>= 6 < 14`

**Comment by jods4** [comment]
@implausible I didn't intend to be aggressive or insulting. Please keep in mind I'm not a native English speaker so I apologise if some phrasing was out of place. BTW it would help me not repeat the same mistakes if you could point me what part was really inappropriate and threw you off.

For example you say I'm making a request but there is no direct request, I did not even open a new issue. I just asked when you're gonna publish new binaries for Node 14, given you previously said you only provide binaries for even releases. 
Knowing you're too busy to publish a prebuilt binary I'll act accordingly on my side.

I certainly appreciate the work you put into an open-source component and I sincerely thank you for that.

I have contributed to OSS myself and I know that life can be very busy and it's hard to keep pace with users' demand. You owe us nothing, take some time for yourself: your health and well-being is more important than software.

As for the install part: I don't imply that it's overly complex but we may not share the same definition of "incredibly easy". It's your own words and I respectfully disagree with you.

To me "incredibly easy" means that you do `npm i yourlib` and it just works, on everyone's machine.
The moment you said: 
>You might want to review the documentation there to get some insight into what dependencies you need to build for Node 14. I would also recommend you read our README.md for any additional build time dependencies you might need.

You lost me on the "incredibly easy" part.
Having to read docs and install some 3rd party dependencies is something I'm able to do but it's not an easy, out-of-the-box experience.
It matters because my coworkers will have to do the same otherwise they'll get an error when they pull my changes and they'll get angry at me; our CI must be configured appropriately as well, etc.

I didn't mention this to angry you or argue that it's too hard for what it is.
I mentioned it because _"NodeGit can be quickly and painlessly installed via NPM."_ is the first thing I see at the top of NodeGit homepage. It's what you choose to put forward.

I still like you and I'm thankful for your work, please don't get mad 🧸

**Comment by gnu4cn** [comment]
Now I am on Ubuntu 16.04, `krb5-config` not exists, but there is `krb5-config.mit` you will find, thru cli TAB auto complete, and `which krb5-config.mit`, you will find `/usr/bin/krb5-config.mit`, now all you need to do is `sudo ln -s /usr/bin/krb5-config.mit /usr/bin/krb5-config`, Bingo....

**Comment by implausible** [comment]
For windows have you tried installing https://npmjs.com/pcakage/windows-build-tools ?

**Comment by billinghamj** [comment]
On modern Ubuntu:

```
sudo apt-get install libkrb5-dev -y
```

Given how important this lib is, it would seem like it would be very beneficial to the community if it could get more consistent support - are there other maintainers or projects which have worked with this? I see there are some corporate sponsors, I wonder if they could help at all

**Comment by mzedeler** [comment]
Can someone explain why nodegit depends on a *kerberos* utility? I don't see the connection. Thanks!
