### ISSUE TITLE
External HTTPS request to AWS during the installation

### ISSUE THREAD

**Issue by pavelkornev** [nodegit/nodegit#1760]
While installing nodegit in our corporate network (we have some firewall settings), encounter the following error:

```
18:46:33 INFO - > nodegit@0.26.4 install /xmake/j/prod-build10010/w/madmartians/madmartians-eslint-tools-master-CI-linuxx86_64/gen/out/module/node_modules/nodegit
18:46:33 INFO - > node lifecycleScripts/preinstall && node lifecycleScripts/install
18:46:33 INFO - 
18:46:33 INFO - [nodegit] Running pre-install script
18:46:33 INFO - [nodegit] Running install script
18:46:34 INFO - node-pre-gyp
18:46:34 INFO - WARN Using request for node-pre-gyp https download
18:46:35 INFO - node-pre-gyp
18:46:35 INFO - WARN Pre-built binaries not installable for nodegit@0.26.4 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
18:46:35 INFO - node-pre-gyp WARN Hit error connect ECONNREFUSED 52.216.146.163:443
18:46:36 INFO - gyp
18:46:36 INFO - WARN install got an error, rolling back install
18:46:36 INFO - gyp
18:46:36 INFO - ERR! configure error 
18:46:36 INFO - gyp ERR! stack
18:46:36 ERROR - connect ECONNREFUSED 104.20.22.46:443
18:46:36 INFO - gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
18:46:36 INFO - gyp
18:46:36 INFO - ERR! System Linux 4.4.180-94.113-default
18:46:36 INFO - gyp
```

Basically, it seems like someone tries to connect to 52.216.146.163 (s3-1-w.amazonaws.com), this connection fails and the whole installation fails. 

We have no such a problem with any other npm package from public npm repository, so it looks like the request is coming from this library or from one of it's dependency.

**Question:**  do you know what is the nature and the purpose of a such HTTPS  request during the installation phase?

Thx in advance.

**Comment by implausible** [comment]
We actually build and publish prebuilt binaries for NodeGit so that consumers of the library don't have to compile NodeGit locally. Those are stored in s3 at this bucket: https://axonodegit.s3.amazonaws.com/nodegit/nodegit/. We leverage the library [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) to do the fetching from this bucket. You can find out more about leveraging s3 on the documentation for that package.

Make sure to review the dependencies listed in the `README.md` if you for whatever reason can't unblock our s3 bucket so that you can still compile from source on install.
