### ISSUE TITLE
C++14 required in binding.gyp

### ISSUE THREAD

**Issue by Githubber2021** [nodegit/nodegit#1808]
Hi, the latest V8 binaries require C++14. Can we bump this up for the latest Electron version?

That got into affect a while ago but afaik this just came to a recent version of Electron.

https://github.com/nodegit/nodegit/blob/5e04ffa44c3bcc6a978428c40b3fa47cd5cb1451/generate/templates/templates/binding.gyp#L117

**Comment by leinelissen** [comment]
Running into this as well. Apparently the standard was dropped to C++11 fairly recently: https://github.com/nodegit/nodegit/commit/69d9d4e03235a52c13a5bd52d7a5f15aa0481655

This is weird considering that V8, NodeJS and Electron have all been on C++14 for years: https://github.com/nodejs/node/issues/17065, https://www.electronjs.org/blog/electron-2-0

I have attempted to overwrite the build config, but I was unable to figure out a proper way of making a fork (given the disconnect between the NPM package and Git repository, and I cannot overwrite any node-gyp variables. 

This blocks Electron 11 adoption, and thus native Apple Silicon binaries. Given that the fix is fairly trivial, I hope for a speedy fix.
