### ISSUE TITLE
Get commits history only for a file

### ISSUE THREAD

**Issue by creatifDynamics** [nodegit/nodegit#220]
Hi,

how can I get the commits history but only for a particular file, not all the branch ?

thanks !

**Comment by niclashoyer** [comment]
I had a quick look at the [log example from libgit2](https://github.com/libgit2/libgit2/blob/master/examples/log.c) and it seems to use the [git_pathspec_match_tree](https://libgit2.github.com/libgit2/#HEAD/group/pathspec/git_pathspec_match_tree) function to match for a given file. The `Pathspec#matchTree` method in nodegit seems to be the corresponding one. But that method needs a pathspec and
```js
var pathspec = new nodegit.Pathspec();
```
results in
```
Error: A new GitPathspec cannot be instantiated.
```
Is there any way to construct a new pathspec using nodegit?

**Comment by johnhaley81** [comment]
That object will have to be constructed by the libgit2 library. Right now you'd have to be calling something like [git_pathspec_new](https://libgit2.github.com/libgit2/#HEAD/group/pathspec/git_pathspec_new).

Unfortunately we're [ignoring that method right now](https://github.com/nodegit/nodegit/blob/master/generate/input/descriptor.json#L984-L990) and I think it's because we don't have a good way to pull in an array of strings and pipe that through C++/C to get it into libgit2.

That's something we'll have to figure out. If you have any ideas we'd certainly would love the help :)

**Comment by tbranyen** [comment]
Now that `git_strarray` has landed, we should revisit this.
