### ISSUE TITLE
Why node-git uses 90% rotated hexagon?

### ISSUE THREAD

**Issue by 3y3** [nodegit/nodegit#344]
Why node-git uses 90% rotated hexagon instead of classical for nodejs?
What is initial conflict in #69?

**Comment by johnhaley81** [comment]
I think that rotating it the 90% resolved the conflict that we had with joylent ([ref this comment](https://github.com/nodegit/nodegit/issues/69#issuecomment-20257567)(.

**Comment by mcollina** [comment]
Given that the majority of node-related thing now use the hexagon, including Tessel (a company!), nodeschools, nodeconf, etc.. maybe we can fix this?

**Comment by mcollina** [comment]
Given that [iojs](https://iojs.org/) uses that same hexagon, I do not see issues.

**Comment by johnhaley81** [comment]
That's true. We could probably change it now. @isaacdurazo and @tbranyen, since you guys started the logo stuff, what do you think?

**Comment by tbranyen** [comment]
I intentionally engaged Joyent, because I believe they have a right to protect their brand and I have no intention on setting up a conflicting brand that we'd inevitably be legally forced to change.  The problem is/was more than just the hexagon, it was the color, hexagon size/orientation, AND the word Node following it.  That is the problem.  IOJS does not have that same problem.

We agreed on the current brand and changing it to something potentially problematic is pointless at this point :-)

**Comment by 3y3** [comment]
>  The problem is/was more than just the hexagon; it was the color, hexagon size/orientation, AND the word Node following it.

This is a description of Node Inspector logo =)

**Comment by tbranyen** [comment]
@3y3 i'm sure there's more than just Node Inspector, but we extended Joyent a professional courtesy and asked.  They told us *no* and we complied.  Feel free to contact them again on our behalf (speaking for us) and if they oblige I'd be happy to reopen this issue.
