### ISSUE TITLE
Augment `getTagByName` to include `getReferenceCommit`

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#403]

**Comment by maxkorp** [comment]
is it just me, or are all of the getTagByName/getTag/GetBranch/getReference/getBranchCommit methods a bit inconsistant. Seems like they should be normalized a bit, so they all have a getType/getTypeByName/getTypeCommit/getTypeCommitByName variant.

**Comment by johnhaley81** [comment]
Yeah that's a great idea.

**Comment by maxkorp** [comment]
So a bit of an oddity here, we have to remember that "tags" are annotated tags, which are different from lightweight tags, which are what you usually think of when saying tag. Lightweight tags, references in general, branches etc don't have "oids" per se, just the targets and names. Only annotated tags have oids, because they exist inside of the object db. Do we want to rename tags (in the sense of annotated tags) to annotatedTag to make things clear?
That way `tag` can just be for normal tags, like one would expect.

**Comment by johnhaley81** [comment]
I don't know about this. That would be a pretty serious deviation from how we have historically done things with libgit2 (i.e. don't rename groups/classes). I like your previous method more.

**Comment by maxkorp** [comment]
Yeah, just the previous method doesn't exactly make sense, TBH, since only annotated tags have an oid. I suppose we could do getBranch/getBranchCommit/getReference/getReferenceCommit/getTag/getTagCommit, and for any of those if the ref doesnt point at a commit, just return undefined? or try grabbing it and let the chain error out?

**Comment by johnhaley81** [comment]
All of those will point at a commit.
