### ISSUE TITLE
Cannot create an instance of Packbuilder

### ISSUE THREAD

**Issue by stevenceuppens** [nodegit/nodegit#507]
`var packbuilder = new NodeGit.Packbuilder();`
results in -> [Error: A new GitPackbuilder cannot be instantiated.]

From the docs http://www.nodegit.org/api/#Packbuilder , it seems that Packbuilder only has Instance methods to use Packbuilder, and no Class methods to create an instance of it. I'm also not able to create a "new" instance of Packbuilder from Js, and can't find a reference on other objects to an existing instance.

**Comment by maxkorp** [comment]
Hrm, it seems that git_packbuilder_new is probably ignored. 

If you can, clone the repo, take a look inside out `generate/input/ descriptor.json` file and see if thats set to be ignored. If it is, try taking it out and regenerating/compiling. That should add `NodeGit.Packbuilder.create()`. If that works, submit a PR, preferably with a test (or more) and we'll get it in asap. Otherwise, I'll make sure that gets moved near the top of the stack, but I don't know how quickly it will get implemented.

**Comment by tbranyen** [comment]
FYI I submitted a PR that adds this in: https://github.com/nodegit/nodegit/pull/513

**Comment by maxkorp** [comment]
:+1:

**Comment by tbranyen** [comment]
Closed via: c0922f7169605f986331d85eeb9305244ec095fb

Usage:

``` javascript
var packBuilder = NodeGit.Packbuilder.create();
```
