### ISSUE TITLE
NodeGit.Cred.sshKeyNew: Waiting for USERAUTH response

### ISSUE THREAD

**Issue by lucastschmidt** [nodegit/nodegit#553]
Hey guys I am trying to fetch/clone using *Cred.sshKeyNew*, but I keep getting: 

``Failed to authenticate SSH session: Waiting for USERAUTH response``

Source? https://github.com/karelia/libssh2/blob/master/src/userauth.c

Does anyone know whats going on?

I am using just like https://github.com/nodegit/nodegit/blob/master/test/tests/clone.js#L92-L114

I can get everything to work by using *NodeGit.Cred.sshKeyFromAgent(userName)*. But in my case, I will have to make it work using a private key file.

**Comment by tbranyen** [comment]
"just like" unfortunately our tests pass, so that's not enough to go on.  What's your code look like? Can you paste as much information as possible?

**Comment by lucastschmidt** [comment]
Sorry @tbranyen, I get it. I did try below to paste as much as I could, this is basically the first thing I do, and it fails if I use *sshKeyFromAgent*. 

```
var cloneURL = "ssh://gitosis@server/example.git";

var storageLocalPath = require('path').join(process.cwd(), 'app/git', "static");

var remoteCallbackOptions = {
  certificateCheck: function() {
    return 1;
  },
  credentials: function(url, userName) {
    return NodeGit.Cred.sshKeyNew(userName, path.join(process.cwd(), './git_keys/key.pub'), path.join(process.cwd(), './git_keys/key'), '');
  }
};

var cloneOptions = {
  remoteCallbacks: remoteCallbackOptions
};

NodeGit.Clone(cloneURL, storageLocalPath, cloneOptions).then(function() {
  return console.log("got it");
})["catch"](function(error) {
  return console.error(error);
});

```

I believe that I am calling everything correctly, so, if we assume that, I would need help to try to understand that error code, since, maybe the issue is in my keys or something else. *I did test the key out using:*
```ssh -i path/to/file gitosis@server```

I did try with another key, that I use normally to access that repository, and it *WORKED*. But, I dont know if the issue is related to MacOS, or something like that, since the other key that I am trying is not being used in the OS. 


Thanks for the help!

**Comment by johnhaley81** [comment]
So I'm able to repo that issue on #580 but only when the ssh key is not tied to any account. Did you add the key to an account before you used it?

**Comment by lucastschmidt** [comment]
@johnhaley81 , thats exactly my issue.

The key that worked was one tied to my account already. The one that I need to use, it is not tied to the account, and that is what I need.

**Comment by johnhaley81** [comment]
@lucastschmidt so the error that comes back from libgit2 is pretty cryptic. We're not getting the underlying error from libssh2 that we ought to. I dove into the C code and saw that what's happening is that the server is rejecting authenticating the key because it has no knowledge of the key. Then it polls the same credential callback and gets the same key and gets the same error. It does this until it times out which is where we get the `Waiting for USERAUTH` error which is misleading.

But the first part makes sense and is correct. If you're trying to use a key that the server has no knowledge of then it's going to reject it. There's really nothing we can do on our side to remedy this. If it's a requirement that the server has no knowledge of the SSH key you're trying to use before hand then there's nothing that we can do for you.

If that isn't a requirement then I'd put the key on the server and it should work for you.

**Comment by lucastschmidt** [comment]
@johnhaley81 got it, in my case, the key was suppose to work, it was (supposedly) correctly added in the server, and I was able to test the key using ``ssh -i path/to/file gitosis@server``.

The only thing that I thought may be something to consider is that the key is not associated to my user account in the OS. If I use another key, that is associated to my user account, it works fine. While using this other one, it doesnt.

**Comment by johnhaley81** [comment]
@lucastschmidt if you're using ssh and it has any other keys in there that will authenticate then it will try to use other ones when you fail with the one specified in the path which is probably why it's succeeding. Try removing all other keys from the agent (e.g. renaming `~/.ssh` to something else)
