### ISSUE TITLE
npm rebuild fails (lifecycleScripts/clean should not delete lifecycleScripts!)

### ISSUE THREAD

**Issue by mhart** [nodegit/nodegit#576]
After successfully running `npm install --save nodegit`, a subsequent `npm rebuild` yields:

```console
> nodegit@0.4.0 install /Users/michael/whatever/node_modules/nodegit
> node lifecycleScripts/install


module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/michael/whatever/node_modules/nodegit/lifecycleScripts/install'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

Probably because the install script deletes the lifecycleScripts directory!

https://github.com/nodegit/nodegit/blob/0841799b5d3fe0627aa3c741d65069de6e1798fa/lifecycleScripts/clean.js#L46

**Comment by maxkorp** [comment]
This is already fixed in master. Waiting for one or two other bugs before publishing.

**Comment by mhart** [comment]
Ah, gotcha – sorry, I didn't look at package.json in master.

That line is still in the clean script though – does it make sense that it should delete itself?

**Comment by maxkorp** [comment]
Yeah, I'd think so. The point of that scripts is like a true "kill everything unneeded" deal for maximizing space savings, assuming a completed install. even without, a rebuild will fail (several of the node modules used for installation are removed since theyre not needed for runtime). I'm more tempted to delete the script entirely, since everyone seems to have varying expectations.
