### ISSUE TITLE
Can't install. Gives permission errors?

### ISSUE THREAD

**Issue by huglester** [nodegit/nodegit#606]
Hello,

I try installing nodegit using:
`npm install nodegit` (with sudo result is the same)

```bash
% npm install nodegit             
\
> nodegit@0.4.1 install /home/huglester/tmp/nodegit/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: npm WARN prefer global js-beautify@1.5.6 should be installed with -g
npm WARN prefer global pangyp@2.2.1 should be installed with -g
npm ERR! Linux 3.16.0-41-generic
npm ERR! argv "node" "/home/huglester/tmp/nodegit/node_modules/nodegit/node_modules/.bin/npm" "install" "--ignore-scripts"
npm ERR! node v0.10.38
npm ERR! npm  v2.11.2
npm ERR! path /home/huglester/.npm/js-yaml/3.0.1
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/home/huglester/.npm/js-yaml/3.0.1'
npm ERR!  { [Error: EACCES, mkdir '/home/huglester/.npm/js-yaml/3.0.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/huglester/.npm/js-yaml/3.0.1',
npm ERR!   parent: 'coveralls' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/huglester/tmp/nodegit/node_modules/nodegit/npm-debug.log
] killed: false, code: 3, signal: null }
undefined
nodegit@0.4.1 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)
└── npm@2.11.2
```

I tried installing js-beautify and pangyp globally as suggested - but with no luck.

Maybe you guys have idea on how to set it up?

Thanks!

**Comment by tbranyen** [comment]
You shouldn't be using sudo without `-g` in your `npm install` command.  That will cause permissions issues because it makes directories and files with `root` permissions.  When you then try and run `npm` again as a normal user, npm will be unable to touch those `root` level directories and files.  As you can see this isn't really a NodeGit issue.  My advice would be to try and remove your local `.npm` directory with a command like: `sudo rm -rf /home/huglester/.npm`.  Then try and reinstall with `npm install`.  If the vesion 0.4.1 doesn't work for you, try the previous version with something like `npm install nodegit@0.4.0`.

**Comment by tbranyen** [comment]
BTW these kinds of questions are better asked in our Gitter channel.  You'll find the link in our README, big button at the top.

**Comment by huglester** [comment]
Hello, thanks for explanation. I really manged to get this working.
