### ISSUE TITLE
Check if local branch is up to date with remote

### ISSUE THREAD

**Issue by 5an1ty** [nodegit/nodegit#607]
I currently use the pull example to update my local copy to the remote. But how do I check if an update is needed, because currently it's always running fetch and mergeBranches even when it's not needed.

**Comment by jdgarcia** [comment]
The fetch is needed in order to make sure your origin branch is up to date. You will always need it otherwise there's no way of knowing if there's any new commits or not.  As for mergeBranches, it seems that function already checks for you if anything needs to be done before actually attempting the merge.

See here: https://github.com/nodegit/nodegit/blob/090634f8ebbbc34a70e4466e6660f77a74241d37/lib/repository.js#L688

**Comment by 5an1ty** [comment]
Thanks!
