### ISSUE TITLE
clone in express route not exiting.. (for large repo)

### ISSUE THREAD

**Issue by msreekm** [nodegit/nodegit#768]
Below route in node.js prints clone completed, but not sending the response back to calling clients. I tested the same code in node command line and it worked.  Also noticed that while the clone is in progess ,it repeatedly calls this route over and over.. not sure why that is happening also. 

this is the server output when this route runs-
clone start
cloning..
start
clone start  <-- (**note the second recursive call here)
clone completed
(at this point browser is still waiting for response)

code

router.get('/CloneRepository', function (req, res, next) {
    console.log('clone start');

    var cloneOptions = {};
    var cloneComplete = false;
    fs.exists(repoPath, function (exists) {
        if (!exists) {
            console.log('cloning..');

            // clone into tmp folder
            var url = 'https://stash.xxx.com/scm/stp/salesforce.git'

            var clone = nodeGit.Clone.clone,
                userpassPlaintextNew = nodeGit.Cred.userpassPlaintextNew,
                user = 'XXX',
                pass = 'XXX',
                path = repoPath,
                options = {
                    remoteCallbacks: {
                        credentials: function () {
                            return userpassPlaintextNew(user, pass);
                        }
                    }
                };

            function url() {
                var url = 'https://';
                url += encodeURIComponent(user);
                url += ':';
                url += encodeURIComponent(pass);
                url += '@stash.xxx.com/scm/stp/salesforce.git';
                return url;
            }
            var surl = url();
            console.log('start');
            clone(surl, path, options)
                .then(function (repo) {
                    console.log('clone completed');
                    res.json('{success}');
                });

        }

    });
});

**Comment by msreekm** [comment]
I temporarily fixed this issue by moving the method out of router and putting it in a helper class.

**Comment by maxkorp** [comment]
I don't know how this would be calling the route again from inside itself, Without a bit more code (at least the basics of your route) there's not much any of us can do about this. 
A few things seem out of scope, but I'm assuming they come from elsewhere in the route. 

Since you said you've been able to get it to work when factored out into a helper, I'm going to mark this closed. If moving it back is a priority for you, try to provide a more complete code example (I realize privacy can be an issue here, so perhaps try stripping it down and pointing at a large public repo) and we can reopen this for you and take a closer look :+1:
