### ISSUE TITLE
latest release has undocumented dependencies

### ISSUE THREAD

**Issue by deyhle** [nodegit/nodegit#826]
So I just updated via npm, which got me version 0.6.0. This returns 

    /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /path/to/myproject/node_modules/nodegit/build/Release/nodegit.node)

While everything worked fine with 0.5, I assume the update to 0.6 did this. Researching the issue, I only found that http://www.nodegit.org/ lists 0.5.0 as latest release, and the changelog that is linked there even lists 0.4.0 as latest release. 
I would expect a current changelog that lists this breaking change. Also, when following SemVer (which is conventional on npm), an update 0.5.0 -> 0.6.0 should not have breaking changes at all.

**Comment by tbranyen** [comment]
@deyhle I just installed nodegit@0.6.0 with Arch Linux (and Ubuntu) running gcc 5.1.0 and 4.8.4 respectively. We've always had a libstdc++ dependency, this is nothing new. I'm not sure why yours is erroring, can you provide a bit more details?

*Obviously we try and minimize breakage between releases, we continuously test (pretty much maxing out AppVeyor and Travis-CI), but that's never enough.* Our changelog says 0.4, because the last stable was 0.5 (we'll move that to the changelog soon). The site is automatically updated now via a Travis-Ci script, but doesn't know enough to update version numbers, we'll have to go in and manually do that.

**Comment by deyhle** [comment]
I'm running Ubuntu 14.04 LTS and have the latest available libstdc++ version installed:

    $# apt-get update
    […]
    
    $# apt-get install libstdc++6
    […]
    libstdc++6 is already the newest version.
    
    $# apt-cache show libstdc++6
    […]
    Version: 4.8.4-2ubuntu1~14.04

After a downgrade to 0.5, it works again. What is the exact requirement?

**Comment by johnhaley81** [comment]
@deyhle so this was a problem with the deploy. When we deployed 0.6.0 the deploy failed in CI so I manually built and published the binaries. I built the linux ones on box with an older version of libstdc++6 on it which is how the requirement stealthed in. I just republished binaries that don't have this requirement. Can you check again to see if this fixes your issue? So sorry about that.

**Comment by deyhle** [comment]
It works now with 0.6.0, great! Just had to re-install it. Thank you very much for the quick fix!
