### ISSUE TITLE
Bad password in credentials locks out account?

### ISSUE THREAD

**Issue by ry99** [nodegit/nodegit#901]
I'm calling `Cred.userpassPlaintextNew( username, password )` from within the credentials callback during network operations. However if you use the wrong password, the callback keeps getting called, and your account will eventually be locked out.

I believe we need a way to interrupt/cancel this.

**Comment by maxkorp** [comment]
There's definitely a way to escape out of this, as we already do that in GitKraken. Pinging @cbargren

**Comment by cbargren** [comment]
Yeah, I believe it's done this way to allow for user input within the credentials callback. Whatever you pass into the credentials callback is what it's going to use, regardless of whether it's been tried and failed before. If you return `NodeGit.Cred.defaultNew()` in the credentials callback, the action will reject instead of trying to get your credentials again (assuming `defaultNew` credentials aren't valid for that remote), so you can use that to interrupt the credentials cycle. If you're specifying your credentials programmatically, you'll need to provide a way to remember whether you've tried those credentials before so you can escape instead of attempting the credentials again. Something like this might work:

``` javascript
var credentialsAttempted = false;
var password = '<your password>';
var options = {
  callbacks: {
    credentials: function(url, username, allowedTypes) {
      if (credentialsAttempted) {
        // we already tried the credentials we have and they didn't work, just fail
        return NodeGit.Cred.defaultNew();
      }
      credentialsAttempted = true;
      return NodeGit.Cred.userpassPlaintextNew(username, password);
    }
  }
};
```

**Comment by ry99** [comment]
Awesome! Works perfectly. Thanks.
